config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]

  resources :users
  resources :games

  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id            :bigint           not null, primary key
#  date_played   :date
#  win_by_mate   :boolean
#  winning_color :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  black_id      :integer
#  game_type_id  :integer
#  white_id      :integer
#

class Game < ApplicationRecord
  validates :date_played, :white_id, :black_id, :game_type_id, :winning_color, presence: true

  belongs_to :white_player, foreign_key: :white_id, class_name: :User
  belongs_to :black_player, foreign_key: :black_id, class_name: :User
  
  belongs_to :game_type
end

app/models/game_type.rb
# == Schema Information
#
# Table name: game_types
#
#  id         :bigint           not null, primary key
#  game_type  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class GameType < ApplicationRecord
  validates :game_type, presence: true, uniqueness: true

  has_many :games
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  firstName       :string
#  image_url       :string
#  lastName        :string
#  password_digest :string
#  session_token   :string           not null
#  username        :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_session_token  (session_token) UNIQUE
#

class User < ApplicationRecord
  validates :firstName, :lastName, :image_url, :session_token, :username, presence: true

  has_many :white_games, foreign_key: :white_id, class_name: :Game
  has_many :black_games, foreign_key: :black_id, class_name: :Game

  attr_reader :password

  before_validation :ensure_session_token!, :ensure_username!

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    user&.is_password?(password) ? user : nil
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def reset_session_token!
    update!(session_token: SecureRandom::urlsafe_base64(16))
    session_token
  end

  def ensure_session_token!
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end

  def ensure_username!
    self.username = "#{firstName}_#{lastName}".downcase if username.nil? || username.empty?
  end
  # has_many :games, ->(game) { where('white_id = ? OR black_id = ?', user_id, user_id) }

  def games
    (white_games + black_games).sort { |a, b| a.date_played <=> b.date_played }
  end

  def name
    "#{firstName} #{lastName}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end
end

app/controllers/game_types_controller.rb
class GameTypesController < ApplicationController
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def create
    @game = Game.new(game_params)

    if @game.save
      flash[:notice] = "Successfully saved game"
    else
      flash[:errors] = @game.errors.full_messages.join('');
    end

    redirect_to users_url
  end

  private
  def game_params
    params.require(:game).permit(:date_played, :white_id, :black_id, :winning_color, :win_by_mate, :game_type_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by_credentials(params[:user][:username],
                                    params[:user][:password])

    if user
      login_user!(user)
      redirect_to root_url
    else
      flash.now[:errors] = ['Invalid credentials.']
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil

    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # @users = User.all.includes(:games)
    @users = User.all.includes(white_games: [:white_player, :black_player], black_games: [:white_player, :black_player])
    # @users = User.all.includes(:white_games, :black_games).order(:firstName, :date_played)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_types_helper.rb
module GameTypesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://use.fontawesome.com/daf11ff38a.js"></script>

    <title>ChessClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="main-page">
    <div class="nav-bar">
      <div class="flash-messages">
        <%= flash[:notice] if flash[:notice] %>
        <%= flash[:errors] if flash[:errors] %>
      </div>
    </div>

    <%= yield %>

    <footer>
      <span>Chess Club. Created by Scott Ha and Nathan Mendes</span>
      <span class="social-media-links">Social Media Links</span>
      <ul class="footer-links">
        <li><a href="https://github.com/AA-ScottHa/ChessClub"><i class="fa fa-github" aria-hidden="true"></i> Chess Club GitHub</a></li>
        <li><a href="https://github.com/mendesnathanj"><i class="fa fa-github" aria-hidden="true"></i> Nathan Mendes</a></li>
        <li><a href="https://github.com/AA-ScottHa/"><i class="fa fa-github" aria-hidden="true"></i> Scott Ha</a></li>
      </ul>

    </footer>
  </body>
</html>

app/views/users/index.html.erb
<div class="players">
  <h1>All Players</h1>
  <ul class="player-list">
  <% @users.each do |user| %>
    <li class="player-info">
      <span>lililil</span>
      <img class="player-image" src="<%= user.image_url %>" alt="<%= user.firstName %>">
      <div class="player-description">
        <h2 class="player-name"><%= "#{user.firstName} #{user.lastName}"%></h2>
        <% user.games.each_with_index do |game, idx| %>
          <div class="game-info">Game <%= idx+1 %>:
          <p><span class="white-player"><%= game.white_player.firstName %></span> versus <span class="black-player"><%= game.black_player.firstName %></span></p>
          <p><span class="<%= game.winning_color %>-player"><%= game.winning_color.upcase %></span></p>
          <p><%= game.date_played %></p>
          </div>
        <% end %>
      </div>
    </li>
  <% end %>
  </ul>
</div>
<div class="add-new-game-div">
  <button>Add New Game</button>
  <div class="add-new-game-info">
    <%= form_for :game, url: games_url, method: 'POST' do |f| %>
      Date: <%= f.date_field "date_played", value: Date.today %><br>
      White Player: <%= f.select "white_id", options_from_collection_for_select(@users, "id", "name") %><br>
      Black Player: <%= f.select "black_id", options_from_collection_for_select(@users, "id", "name") %><br>
      Winner: <%= f.select "winning_color", options_for_select(['black', 'white']) %><br>
      Win By Mate? <%= f.check_box "win_by_mate" %><br>
      Game Type: <%= f.select "game_type_id", options_from_collection_for_select(GameType.all, "id", "game_type") %><br>
      <%= f.submit "Submit Game" %>
    <% end %>
  </div>
</div>